Insert into categories(name, description) values ('Sport', 'Sport category');
Insert into categories(name, description) values ('Movie', 'Movie category');
Insert into categories(name, description) values ('Music', 'Music category');
Insert into categories(name, description) values ('Science', 'Science category');
Insert into categories(name, description) values ('Animal', 'Animal category');
Insert into categories(name, description) values ('Art', 'Art category');
Insert into categories(name, description) values ('Travel', 'Travel category');
Insert into categories(name, description) values ('Book', 'Book category');
Insert into categories(name, description) values ('Other', 'Other category');