version: '3.1'

services:
  rest:
    image: quizzy/rest-api
    container_name: rest-api
    build: ../backend - REST API/
    ports:
      - 8080:8080
    environment:
      -SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test
      -SPRING_DATASOURCE_USERNAME: test
      -SPRING_DATASOURCE_PASSWORD: test
    depends_on:
      - db

  db:
    image: postgres:${POSTGRES_TAG}
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    command: "
              postgres
                -c max_connections=200
                -c logging_collector=on
                -c log_min_messages=LOG
                -c log_directory=/var/log/postgresql"
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql